import React from 'react';
import NavBar from '../components/Navbar/Navbar';
import Head from 'next/head';
import Footer from '../components/Footer/Footer';
import InfoCheckout from '../components/InfoCheckout/InfoCheckout';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faChevronRight } from '@fortawesome/free-solid-svg-icons';

const checkout = () => {
  const dataPage = { page: 'products' };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://use.typekit.net/wxl3mdd.css"></link>
        <link rel="stylesheet" href="https://use.typekit.net/jfy4rte.css"></link>
      </Head>
      <NavBar page={dataPage} />
      <InfoCheckout />
      <Footer />
    </>
  );
};

export default checkout;
