import React, { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import { getFirestore } from '../../utils/firebase';
import Image from 'next/image';
import Head from 'next/head';
import Counter from '../components/Counter/Counter';
import Navbar from '../components/Navbar/Navbar';
import Footer from '../components/Footer/Footer';

const SingleProduct = () => {
  const dataPage = { page: 'products' };
  const [product, setProduct] = useState({});
  const [loading, setLoading] = useState(true);
  const router = useRouter();
  const { id } = router.query;

  return (
    <>
      <Head>
        <title>Single Product</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://use.typekit.net/wxl3mdd.css"></link>
        <link rel="stylesheet" href="https://use.typekit.net/jfy4rte.css"></link>
      </Head>
      <Navbar page={dataPage} />
      <Counter />
      <Footer />
    </>
  );
};

export default SingleProduct;
